---
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: Ensure Pip is latest.
  pip:
    name: "pip"
    executable: "{{ pip_executable }}"
    state: latest
    
- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  with_items: "{{ pip_install_packages }}"
